### ISSUE TITLE
Stylelint errors not showing up in webpack build output

### ISSUE THREAD

**Issue by ericmarkmartin** [danbruegge/gatsby-plugin-stylelint#2]
I installed the plugin and setup `stylelint` (my configuration below), and there's a line that stylelint, when run manually, flags, but nothing shows up in the gatsby log.

`.stylelintrc.yaml`
```yaml
processors:
  - stylelint-processor-styled-components
extends:
  - stylelint-config-standard
  - stylelint-config-prettier
  - stylelint-config-styled-components
```

**Comment by danbruegge** [comment]
Hej. Sorry for being late. Did you found a solution?

Thats my `.stylelintrc`:
```json
{
  "processors": ["stylelint-processor-styled-components"],
  "extends": [
    "stylelint-config-recommended",
    "stylelint-config-styled-components"
  ],
  "syntax": "scss"
}
```

Maybe it is an yaml problem? Never used yaml before.

**Comment by danbruegge** [comment]
I've tried my config with yaml and it worked.

```yaml
processors:
  - stylelint-processor-styled-components
extends:
  - stylelint-config-recommended
  - stylelint-config-styled-components
syntax:
  - scss
```
File edit:
![gatsby-plugin-stylelint-code-example](https://user-images.githubusercontent.com/1296438/47503544-addee880-d86a-11e8-81a1-991841fddbdb.png)

Server output:
![gatsby-plugin-stylelint-server-output](https://user-images.githubusercontent.com/1296438/47503559-b59e8d00-d86a-11e8-94e5-3670932681fc.png)
